### PR TITLE
feat: update to angular 18, standalone app and zoneless

### PR DESCRIPTION
**Pull request by sheikalthaf**
- update to Angular 18
- make app standalone application
- make app zoneless
- following Angular versioning
- using pnpm as package manager

### CODE REVIEW

**Comment by sheikalthaf** [comment]
@santoshyadavdev once you are free please review this PR

**Comment by Yberion** [comment]
Hello @santoshyadavdev, any news regarding this PR? ^^

**Comment by santoshyadavdev** [comment]
Hey buddy, 

I am still in India and travelling, if possible can you do one round of review.

I will be back in 2 weeks and have a look at it.

**Comment by sheikalthaf** [comment]
Hi @santoshyadavdev,

Can you review the PR

**Review by santoshyadavdev — APPROVED** [review]
Great work

**Pull request merged**
