### PR TITLE
Fix ObjectUnsubscribedError on destroy when onInitialDelay is not yet…

### PR DESCRIPTION
**Pull request by JHeidinga**
… reached. The setTimeout function fires after the component is destroyed. Added a clearTimeout and a this.onInitialDelay variable

### CODE REVIEW

**Comment by sheikalthaf** [comment]
@JHeidinga Hi,

Nice to see the fix. I'm currently working on some major update you can try it in branch `ng6-revamp`.

Thanks

**Comment by JHeidinga** [comment]
@sheikalthaf I think you are looking for the delay operator https://www.learnrxjs.io/operators/utility/delay.html I could look into it if you still need it in the revamp

**Comment by sheikalthaf** [comment]
@JHeidinga sure. Because need to avoid the settimeout in favor of rxjs

**Comment by nhatzbulawan** [comment]
Just want to follow this thread for fixes....

**Pull request closed without merging**
