### PR TITLE
Update structure of carousel component to be A11y compatible

### PR DESCRIPTION
**Pull request by thomasnisole**
Hello all,

My pull request is about accessibility. Your carousel is not compatible with the order applied by browsers during keyboard navigation. 
PR only modifies the previous button placement to have a more logical navigation.

Thx,
Thomas.

### CODE REVIEW

**Comment by santoshyadavdev** [comment]
Thank you, will get it released tomorrow.

**Comment by thomasnisole** [comment]
Hello @santoshyadavdev ,

Thank you for merging. 
Have you had the time to release a new version ?

Thx.
Thomas.

**Comment by santoshyadavdev** [comment]
Hey @thomasnisole, 

Will do it today 😊, thank you for the PR again.

**Comment by santoshyadavdev** [comment]
Available in 3.0.2 please try and let us know.

**Pull request merged**
