### PR TITLE
Upgrade to Angular 8

### PR DESCRIPTION
**Pull request by DanVLopes**
I upgraded the project and APP to Angular 8.
I followed the update process recommended by Angula.io and change to new formats of ViewChild and ContentChild

### CODE REVIEW

**Comment by kolkov** [comment]
Hi! Fix this please in your PR.
https://github.com/sheikalthaf/ngu-carousel/issues/159

**Comment by DanVLopes** [comment]
I made the adjustment as indicated

**Comment by hyperativa** [comment]
@sheikalthaf  there is any changes that you recommended to solve the issue #163 and get this changes released on NPM package?

**Comment by magnattic** [comment]
Are there any news? Is this project still actively being maintained?
The fact that this library is not ready for ivy is blocking us from upgrading right now.

**Comment by hyperativa** [comment]
@sheikalthaf could you please validate and prove the PR?

**Comment by doliG** [comment]
@sheikalthaf Hello world

**Comment by kolkov** [comment]
I think we need to change maintainer. :(

**Comment by kolkov** [comment]
https://github.com/isaacplmann/ngx-tour/issues/186 last activity...

**Comment by santoshyadav198613** [comment]
Hey everyone, sorry for the delay on this PR, we have a new release for Angular 9.
And this library will be actively maintained now.

**Comment by santoshyadav198613** [comment]
If you want we can release one for Angular 8, otherwise close this PR.

**Pull request closed without merging**
