### PR TITLE
chore: only support Angular 14

### PR DESCRIPTION
**Pull request by Yberion**
Hello,

### Problem

I think I did a mistake when I tested the lib on my previous PR about updating to Angular 14 https://github.com/uiuniversal/ngu-carousel/pull/379.

What I did was:

- Testing the lib compiled with `Angular 13` on an `Angular 13` demo app
- Testing the lib compiled with `Angular 14` on an `Angular 14` demo app

What I did not:

- Testing the lib compiled with `Angular 14` on an `Angular 13` demo app

And it seems that using a compiled version of the lib with `Angular 14` isn't compatible with an `Angular 13` app.

```
TypeError: Cannot create property 'message' on string 'D:\GitHub\Angular13Project\node_modules\@ngu\carousel\fesm2015\ngu-carousel.mjs: This application depends upon a library published using Angular version 14.1.3, which requires Angular version 14.0.0 or newer to work correctly.
Consider upgrading your application to use a more recent version of Angular.
  82 | }
  83 | NguCarouselItemDirective.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "14.1.3", ngImport: i0, type: NguCarouselItemDirective, deps: [], target: i0.ɵɵFactoryTarget.Directive });
> 84 | NguCarouselItemDirective.ɵdir = i0.ɵɵngDeclareDirective({ minVersion: "14.0.0", version: "14.1.3", type: NguCarouselItemDirective, selector: "[NguCarouselItem]", ngImport: i0 });
     |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^39m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^39m^^^^^^^^^^^^^^^^^^^
```

### Changes

This PR does:

- Only support Angular 14

### Other solution

Another solution could be to compile the lib with `Angular 13` but still support `Angular 14` (`^13.0.0 || ^14.0.0`), but I did not test it. If you wish, I can test it tomorrow. The down side would be to have an `Angular 13` version of the repo on another branche. Maybe there's another solution, I'm not familiar enough with compiled version compatibility of libs.

I'm sorry, I wasn't expecting that behavior 😢.
I don't know what's the best solution, remove the current 6.0 and make a new one or bump to 6.1 (or any version you want).

Have a good day/night.

@santoshyadavdev

### CODE REVIEW

**Comment by santoshyadavdev** [comment]
thanks @Yberion can you also update 
https://github.com/uiuniversal/ngu-carousel/blob/master/projects/ngu-carousel/README.md
and 
https://github.com/uiuniversal/ngu-carousel/blob/master/README.md

**Comment by Yberion** [comment]
Hello @santoshyadavdev, I've updated both readme.

Thanks for the fast answer!

**Review by santoshyadavdev — APPROVED** [review]
thank you

**Comment by santoshyadavdev** [comment]
use 6.0.1

**Pull request merged**
