### PR TITLE
Revert "fix: check length only on unwrapped data (#442)"

### LINKED ISSUE #453: #442 breaks with onpush issues
(this is coming from code inside Google's internal code base, we use ngu-carousel for some of our Angular applications)

**Describe the bug**
#442 breaks initial carousel loading in an OnPush enabled application, where the carousel items do not render until you tab into the carousel via keyboard (as keyboard events trigger a change detection event)

The commit right before it [fc0f98580590355d8a078b2f71c7a902e8d72730](https://github.com/uiuniversal/ngu-carousel/commit/fc0f98580590355d8a078b2f71c7a902e8d72730) works just fine without any issues. The issue I believe is https://github.com/uiuniversal/ngu-carousel/commit/044a29499caff4bf2a9606711b21e8da9fefc570#diff-80e3ec9310b23dec2353dad30b6d6e0d26bf487117733a72fdb8c40c38a95655L190, where there is a time of check vs time of use issue, basically this._unwrappedData is always undefined there, and so the initial ngDoCheck() does nothing, causing this issue.

I'll send out a PR to revert this commit, unfortunately it will break some users that rely on newer functionality but I think it's better so that older users don't have a bug on a simple upgrade.

@arturovt @santoshyadavdev

### PR DESCRIPTION
**Pull request by chivesrs**
This reverts commit 044a29499caff4bf2a9606711b21e8da9fefc570 and a3b7f50844a3e3133b59f00b65d65d5fb6bb736f.

Fixes #453

@santoshyadavdev

### CODE REVIEW

**Comment by chivesrs** [comment]
@santoshyadavdev just checking on this

**Comment by santoshyadavdev** [comment]
> @santoshyadavdev just checking on this

I was travelling let me take a look

**Comment by santoshyadavdev** [comment]
> [chivesrs](/chivesrs)

BTW our sample app seems to use OnPush strategy and works fine.

**Comment by chivesrs** [comment]
@santoshyadavdev what do you reckon we should do here? Should I rebase and do my best to get the commit reverted and fix merge conflicts? Something else?

**Comment by santoshyadavdev** [comment]
Hey buddy, Sorry I just came yesterday from a conference, I will merge this one, can you resolve the conflict please.

**Comment by chivesrs** [comment]
I've resolved the merge conflict but unfortunately had to revert #458, I tried to preserve the PR as best as I could but I think it depends too much on the changes from #442. I manually brought forward the changes but they didn't work so I think it's safer to have @luca-peruzzo do their fix after this one goes through.

@santoshyadavdev lmk your thoughts

**Comment by luca-peruzzo** [comment]
Hi @chivesrs, did you try my changes with ChangeDetectionStrategy.OnPush? I think there is no need for _unwrappeddata.
Do you have a sample app where I can try to solve the OnPush Issue (if it persists)?

**Comment by chivesrs** [comment]
@luca-peruzzo the code I have is internal to Google so it's not super easy for me to post it here. I tried your changes out yes on both my app and the sample app in this repo. It worked on the sample app but not on mine. We basically just have one data array and the issue I have is the entire carousel doesn't render until I use the tab key to get into where the next/previous buttons would be, and that causes a change detection cycle which finally renders everything.

I'm open to any suggestions you have but #442 was the one that broke us, and I couldn't port forward #458 easily, as when I did port it forward, the fix didn't work in the sample app.

**Comment by chivesrs** [comment]
@santoshyadavdev lmk what you think

@luca-peruzzo it may be best you rebase your fix on top of this PR?

**Comment by santoshyadavdev** [comment]
I am with @luca-peruzzo on this one, Its hard to decide if we should rollback without a proper reproduction of the issue,

@chivesrs  If we can get a small reproduction, it can help to fix this. We don't want the entire code, just a small reproduction.

**Comment by chivesrs** [comment]
We just have a raw array of objects, we don't pass in an observable. I will see what I can do about getting you a repro.

**Comment by Yberion** [comment]
Hello, I've also noticed some problem on my side, what's the plan regarding this MR ? ^^

**Comment by santoshyadavdev** [comment]
Hey @Yberion we are actually looking for a reproduction to see the actual issue and fix.

Can you create one if possible

Thant would be a great help.

**Comment by chivesrs** [comment]
Sorry just been super caught up with non work stuff, getting you a repro is still on my todo list.

**Comment by santoshyadavdev** [comment]
> Sorry just been super caught up with non work stuff, getting you a repro is still on my todo list.

Thank you 😊

**Comment by luca-peruzzo** [comment]
@chivesrs @santoshyadavdev I finally find a way to reproduce the issue. Working in ngu-carousel-example folder, firstly I had to change all components change detection strategy to OnPush and after I created a wrapper component that accepts input datasource and config for ngu-carousel. 
html:
```
<div class="wrapped-carosuel" *ngIf="carouselTileItems.length">
  <h2>Wrapped Carousel</h2>
  <ngu-carousel #myCarousel [inputs]="config" [dataSource]="carouselTileItems">
    <button NguCarouselPrev class="leftRs" [style.opacity]="myCarousel.isFirst ? 0.5 : 1">
      &lt;
    </button>

    <ngu-tile *nguCarouselDef="let item; index as i; let ani = animate" [@slider]="ani">
      <ng-container *ngIf="i % 2 === 0">
        <ng-container
          *ngTemplateOutlet="card; context: { $implicit: item, index: i }"
        ></ng-container>
      </ng-container>
      <ng-container *ngIf="i % 2 !== 0">
        <div class="tile" [style.background]="'url(' + item + ')'">
          <h1>Odd: {{ i + 1 }}</h1>
        </div>
      </ng-container>
    </ngu-tile>

    <button NguCarouselNext class="rightRs" [style.opacity]="myCarousel.isLast ? 0.5 : 1">
      &gt;
    </button>

    <ul class="myPoint" NguCarouselPoint>
      <li
        *ngFor="let i of myCarousel.pointNumbers"
        [class.active]="i === myCarousel.activePoint"
        (click)="myCarousel.moveTo(i)"
      ></li>
    </ul>
  </ngu-carousel>
</div>

<ng-template #card let-item let-i="index">
  <div class="tile" [style.background]="'url(' + item + ')'">
    <h1>Even: {{ i + 1 }}</h1>
  </div>
</ng-template>
```
ts:
```
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  Input,
  OnChanges,
  SimpleChanges
} from '@angular/core';
import { NguCarouselConfig } from '@ngu/carousel';
import { slider } from '../../slide-animation';

@Component({
  selector: 'app-wrapped-carousel',
  templateUrl: 'wrapped-carousel.component.html',
  styleUrls: ['./wrapped-carousel.component.scss'],
  animations: [slider],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class WrappedCarouselComponent implements OnChanges, AfterViewInit {
  @Input() carouselTileItems: any[];
  public config: NguCarouselConfig = {
    grid: { xs: 1, sm: 2, md: 3, lg: 4, xl: 4, all: 0 },
    gridBreakpoints: { sm: 480, md: 768, lg: 1024, xl: 1280 },
    speed: 750,
    point: {
      visible: true
    },
    velocity: 0.1,
    touch: true,
    easing: 'cubic-bezier(0, 0, 0.2, 1)'
  };
  @Input() grid: { xs?: number; sm?: number; md?: number; lg?: number; xl?: number; all?: number } =
    { xs: 1, sm: 2, md: 3, lg: 4, xl: 4, all: 0 };
  constructor(private cd: ChangeDetectorRef) {}

  ngOnChanges(changes: SimpleChanges) {
    if (!!changes?.grid) {
      this.config.grid = changes?.grid?.currentValue || {
        xs: 1,
        sm: 2,
        md: 3,
        lg: 4,
        xl: 4,
        all: 0
      };
    }
  }
  ngAfterViewInit(): void {
    this.cd.detectChanges();
  }
}

```
This particular configuration triggers ngDoCheck only once but _defDirectives is undefined, so we never call renderNodeChanges()

**Comment by santoshyadavdev** [comment]
Thank you @luca-peruzzo I will check. This is really useful.

**Comment by chivesrs** [comment]
Thank you so much for reproducing. Yes, our components are structured similarly, everything is OnPush and we have the carousel wrapped in a few parent components, and they get their data via Angular HttpClient.

Your findings seem similar to what I had stated in #453 right?

**Comment by santoshyadavdev** [comment]
@luca-peruzzo that would be great I can merge and get it released today.

**Comment by luca-peruzzo** [comment]
> @luca-peruzzo that would be great I can merge and get it released today.

Ok, do you want also the reproduction environment with server-side rendering in the PR?

**Comment by santoshyadavdev** [comment]
If we can that's great, or if you want  to add it in another PR that will work too.

Whatever works for you. I am happy to accept the PR.

**Pull request closed without merging**
